services:
  - type: web
    name: crm-strom
    env: node
    buildCommand: npm install && npm run build && npm run build:css
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production

